version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello wowwaaa"
      - run:
          name: Running background after exit fail
          command: sleep 10 && exit 1
          background: true
      - run: sleep 11 && echo "aaaa"
